services:

  mysql:
    image: mysql:latest
    container_name: celi-express-database
    environment:
      MYSQL_DATABASE: celi_express
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    container_name: celi-express-redis
    ports:
      - 6379:6379

  app:
    build: .
    image: celi-express-app
    container_name: celi-express-app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports: 
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/celi_express
      REDIS_HOST: redis
      REDIS_PORT: 6379